spring:
  datasource:
    url: jdbc:oracle:thin:@202.20.119.117:1521:orcl
    username: sw0206
    password: sw0206
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update # 테이블 확정되면 update 로 변경
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    database: oracle


file:
  dir: somsea\src\main\resources\static\images\items\
